name: App Deploy to Vercel
on:
  pull_request:
    branches:
      - main
      
      
jobs:
  issue_comment:
    uses: ./.github/workflows/cctweb-issuecomment.yml
    with:
      issue_number: ${{ github.event.issue.number }}
      owner: ${{ github.repository_owner }}
      repo: ${{ github.event.repository.name }}

