name: App Deploy to Vercel
on:
  pull_request:
    branches:
      - main
      
      
jobs:
  issuecomment-workflow:
    uses: ./.github/workflows/cctweb-issuecomment.yml
    with:
      issue_number: ${{ github.event.pull_request.number }}
      owner: ${{ github.repository_owner }}
      repo: ${{ github.event.repository.name }}
      body: 'sur'
  dev-deploy:
     needs: issuecomment-workflow
     uses: ./.github/workflows/reuseable-workflow.yml
     with:
      environment_name: "development"
      branch: main
      deploy_application: true
     secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
