name: App Deploy to Vercel
on:
  pull_request:
    branches:
      - main
      
      
jobs:
  issuecomment-workflow:
    uses: ./.github/workflows/cctweb-issuecomment.yml
    with:
      #Issue Number: ${{ github.event.issue.number }}
      Owner: ${{ github.repository_owner }}
      Repo: ${{ github.event.repository.name }}
