name: PR-Deploy to Vercel
on:
  pull_request:
    branches:
      - main
jobs:
  Build-deploy:
     uses: ./.github/workflows/reuseable-workflow.yml
     with:
      environment_name: "development"
      branch: main
      deploy_application: true
     secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
