name: PR-Deploy to Vercel
on:
  pull_request:
    branches:
      - main
  push:
    # this will deploy data files only when no release is created
    branches:
      - main
      
      
jobs:
  web-deploy:
     uses: ./.github/workflows/reuseable-workflow.yml
     with:
      environment_name: "development"
      branch: main
      deploy_application: true
     secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
