name: Reusable Workflow

on:
  workflow_call:
    inputs:
      issue_number:
        description: 'The issue number to comment on'
        required: true
        type: number
      vercel_url:
        description: 'The URL to include in the comment'
        required: true
        type: string

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ inputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':bookmark_tabs: The URL for storybook application is: ${{ inputs.vercel_url }}'
            })
